# Câu 1

In [262]:
import pandas as pd
import numpy as np

Đọc dữ liệu từ file

In [263]:
URL=r'https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data' # raw string
df1=pd.read_csv(URL,header=None)
df1.head(10)

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g
5,1,0,0.02337,-0.00592,-0.09924,-0.11949,-0.00763,-0.11824,0.14706,0.06637,...,-0.01535,-0.03240,0.09223,-0.07859,0.00732,0.00000,0.00000,-0.00039,0.12011,b
6,1,0,0.97588,-0.10602,0.94601,-0.20800,0.92806,-0.28350,0.85996,-0.27342,...,-0.81634,0.13659,-0.82510,0.04606,-0.82395,-0.04262,-0.81318,-0.13832,-0.80975,g
7,0,0,0.00000,0.00000,0.00000,0.00000,1.00000,-1.00000,0.00000,0.00000,...,1.00000,1.00000,1.00000,0.00000,0.00000,1.00000,1.00000,0.00000,0.00000,b
8,1,0,0.96355,-0.07198,1.00000,-0.14333,1.00000,-0.21313,1.00000,-0.36174,...,-0.65440,0.57577,-0.69712,0.25435,-0.63919,0.45114,-0.72779,0.38895,-0.73420,g
9,1,0,-0.01864,-0.08459,0.00000,0.00000,0.00000,0.00000,0.11470,-0.26810,...,-0.01326,0.20645,-0.02294,0.00000,0.00000,0.16595,0.24086,-0.08208,0.38065,b

Tổng quan bộ dữ liệu

In [264]:
display(df1.info())
display(df1.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       351 non-null    int64
 1   1       351 non-null    int64
 2   2       351 non-null    float64
 3   3       351 non-null    float64
 4   4       351 non-null    float64
 5   5       351 non-null    float64
 6   6       351 non-null    float64
 7   7       351 non-null    float64
 8   8       351 non-null    float64
 9   9       351 non-null    float64
 10  10      351 non-null    float64
 11  11      351 non-null    float64
 12  12      351 non-null    float64
 13  13      351 non-null    float64
 14  14      351 non-null    float64
 15  15      351 non-null    float64
 16  16      351 non-null    float64
 17  17      351 non-null    float64
 18  18      351 non-null    float64
 19  19      351 non-null    float64
 20  20      351 non-null    float64
 21  21      351 non-null    float64
 22  22      351 non-null    float64
 23  23      351 non-null    float64
 24  24      351 non-null    float64
 25  25      351 non-null    float64
 26  26      351 non-null    float64
 27  27      351 non-null    float64
 28  28      351 non-null    float64
 29  29      351 non-null    float64
 30  30      351 non-null    float64
 31  31      351 non-null    float64
 32  32      351 non-null    float64
 33  33      351 non-null    float64
 34  34      351 non-null    object
dtypes: float64(32), int64(2), object(1)
memory usage: 96.1+ KB

None

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
count,351.000000,351.0,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,...,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000
mean,0.891738,0.0,0.641342,0.044372,0.601068,0.115889,0.550095,0.119360,0.511848,0.181345,...,0.396135,-0.071187,0.541641,-0.069538,0.378445,-0.027907,0.352514,-0.003794,0.349364,0.014480
std,0.311155,0.0,0.497708,0.441435,0.519862,0.460810,0.492654,0.520750,0.507066,0.483851,...,0.578451,0.508495,0.516205,0.550025,0.575886,0.507974,0.571483,0.513574,0.522663,0.468337
min,0.000000,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,1.000000,0.0,0.472135,-0.064735,0.412660,-0.024795,0.211310,-0.054840,0.087110,-0.048075,...,0.000000,-0.332390,0.286435,-0.443165,0.000000,-0.236885,0.000000,-0.242595,0.000000,-0.165350
50%,1.000000,0.0,0.871110,0.016310,0.809200,0.022800,0.728730,0.014710,0.684210,0.018290,...,0.553890,-0.015050,0.708240,-0.017690,0.496640,0.000000,0.442770,0.000000,0.409560,0.000000
75%,1.000000,0.0,1.000000,0.194185,1.000000,0.334655,0.969240,0.445675,0.953240,0.534195,...,0.905240,0.156765,0.999945,0.153535,0.883465,0.154075,0.857620,0.200120,0.813765,0.171660
max,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Vì cột cuối là string (có dtype là object) nên mình sẽ drop đi để xử lý

In [265]:
df1.drop(df1.columns[-1],inplace=True, axis=1)
df1.head(10)

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,0.56811,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.20332,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,0.57528,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,1.00000,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,0.03286,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697
5,1,0,0.02337,-0.00592,-0.09924,-0.11949,-0.00763,-0.11824,0.14706,0.06637,...,0.03513,-0.01535,-0.03240,0.09223,-0.07859,0.00732,0.00000,0.00000,-0.00039,0.12011
6,1,0,0.97588,-0.10602,0.94601,-0.20800,0.92806,-0.28350,0.85996,-0.27342,...,0.22792,-0.81634,0.13659,-0.82510,0.04606,-0.82395,-0.04262,-0.81318,-0.13832,-0.80975
7,0,0,0.00000,0.00000,0.00000,0.00000,1.00000,-1.00000,0.00000,0.00000,...,1.00000,1.00000,1.00000,1.00000,0.00000,0.00000,1.00000,1.00000,0.00000,0.00000
8,1,0,0.96355,-0.07198,1.00000,-0.14333,1.00000,-0.21313,1.00000,-0.36174,...,0.85106,-0.65440,0.57577,-0.69712,0.25435,-0.63919,0.45114,-0.72779,0.38895,-0.73420
9,1,0,-0.01864,-0.08459,0.00000,0.00000,0.00000,0.00000,0.11470,-0.26810,...,-0.14803,-0.01326,0.20645,-0.02294,0.00000,0.00000,0.16595,0.24086,-0.08208,0.38065

## Tính chuẩn 1 cho từng cặp dữ liệu (theo cột)

Hàm pdist cho phép tính khoảng cách giữa các cặp điểm trong một mảng đa chiều, pdist được cài đặt hiệu quả để tính toán khoảng cách giữa các cặp điểm một cách nhanh chóng, đặc biệt đối với các mảng dữ liệu lớn

Hàm squareform sẽ chuyển đổi mảng 1D chứa khoảng cách giữa các cặp điểm (mảng được sinh ra từ hàm pdist) thành ma trận đầy đủ , trong đó giá trị tại hàng i và cột j của ma trận là giá trị khoảng cách giữa cặp điểm i và j trong mảng 1D ban đầu

In [266]:
from scipy.spatial import distance

# Tính ma trận khoảng cách chuẩn 1 (l1 norm) bằng hàm pdist trong thư viện scipy
# Em sẽ không tự code hàm tính khoảng cách cho từng cặp điểm vì với dữ liệu lớn thì dùng hàm có sắn của thư viện (code trên ngôn ngữ C) sẽ hiệu năng tốt hơn rất nhiều 
norm1_distance = distance.squareform(distance.pdist((np.asarray(df1)).T, metric='cityblock'))

# norm1_distance[i,j] là khoảng cách chuẩn 1 (l1 norm) từ i đến j trong ma trận khoảng cách

Kiểm tra shape của ma trận khoảng cách , (34,34) là đúng vì có 34 cột nên sẽ có 34 khoảng cách từ 1 cột đến các cột còn lại (kể cả cột đó), và ma trận này là symmetric vì khoảng cách từ cột i đến cột j cũng bằng khoảng cách từ cột j đến cột i

In [267]:
norm1_distance.shape

(34, 34)

Thử kiểm tra với kết quả so với trong file pdf (Khoảng cách giữa điểm 1 và 2 (cột 0 và 1 ))

In [268]:
norm1_distance[0,1]
# Kết quả là 313.0 bằng với trong file pdf

313.0

## Chuẩn 2 cho từng cặp dữ liệu (theo cột )

In [269]:
from scipy.spatial import distance
norm2_distance=distance.squareform(distance.pdist((np.asarray(df1)).T,metric='euclidean'))

# Ma trận khoảng cách với norm2_distance[i,j] là khoảng cách từ i đến j
norm2_distance

array([[ 0.        , 17.69180601, 10.48097459, ..., 20.46909354,
        14.63557175, 19.4853142 ],
       [17.69180601,  0.        , 15.20107919, ...,  9.60835939,
        11.76661551,  8.76598594],
       [10.48097459, 15.20107919,  0.        , ..., 18.07681495,
        12.81724163, 17.35801695],
       ...,
       [20.46909354,  9.60835939, 18.07681495, ...,  0.        ,
        15.30185023,  9.08258166],
       [14.63557175, 11.76661551, 12.81724163, ..., 15.30185023,
         0.        , 15.30800196],
       [19.4853142 ,  8.76598594, 17.35801695, ...,  9.08258166,
        15.30800196,  0.        ]])

Kiểm tra shape của ma trận khoảng cách , (34,34) là đúng vì có 34 cột nên sẽ có 34 khoảng cách từ 1 cột đến các cột còn lại (kể cả cột đó), và ma trận này là symmetric vì khoảng cách từ cột i đến cột j cũng bằng khoảng cách từ cột j đến cột i

In [270]:
norm2_distance.shape

(34, 34)

Thử kiểm tra với kết quả so với trong file pdf (Khoảng cách giữa điểm 1 và 2 (cột 0 và 1 ))

In [271]:
norm2_distance[0,1]
# Kết quả là 17.69 bằng với trong file pdf

17.69180601295413

Thử kiểm tra với kết quả so với trong file pdf (Khoảng cách giữa điểm 1 và 2 (cột 0 và 1 ))

## Chuẩn vô cùng cho từng cặp dữ liệu (theo cột )

In [272]:
from scipy.spatial import distance
norm_inf_distance=distance.squareform(distance.pdist((np.asarray(df1)).T,metric='chebychev'))

# Ma trận khoảng cách với norm2_distance[i,j] là khoảng cách từ i đến j
norm_inf_distance

array([[0., 1., 2., ..., 2., 2., 2.],
       [1., 0., 1., ..., 1., 1., 1.],
       [2., 1., 0., ..., 2., 2., 2.],
       ...,
       [2., 1., 2., ..., 0., 2., 2.],
       [2., 1., 2., ..., 2., 0., 2.],
       [2., 1., 2., ..., 2., 2., 0.]])

Kiểm tra shape của ma trận khoảng cách , (34,34) là đúng vì có 34 cột nên sẽ có 34 khoảng cách từ 1 cột đến các cột còn lại (kể cả cột đó), và ma trận này là symmetric vì khoảng cách từ cột i đến cột j cũng bằng khoảng cách từ cột j đến cột i

In [273]:
norm_inf_distance.shape

(34, 34)

Thử kiểm tra với kết quả so với trong file pdf (Khoảng cách giữa điểm 1 và 2 (cột 0 và 1 ))

In [274]:
# Khoảng cách giữa 2 điểm 1, 2 (cột 0 và 1 )
print(norm_inf_distance[0,1])
# Kết quả là 1 bằng với trong file pdf

# Khoảng cách giữa 2 điểm 1, 3 (cột 0 và 2)
print(norm_inf_distance[0,2])
# Kết quả là 2 bằng với trong file pdf

1.0
2.0

Em sẽ tính thêm khoảng cách giữa các dòng trong dataframe, vì tính khoảng cách giữa các điểm dữ liệu nó sẽ make sense hơn là tính khoảng cách giữa các cột

In [275]:
norm1_distance = distance.squareform(distance.pdist(np.asarray(df1), metric='cityblock')) # Chuẩn 1
norm2_distance = distance.squareform(distance.pdist(np.asarray(df1), metric='euclidean')) # Chuẩn 2
norm_inf_distance = distance.squareform(distance.pdist(np.asarray(df1), metric='chebychev')) # Chuẩn vô cùng

# Câu 2

In [276]:
import numpy as np
import pandas as pd

Đọc dữ liệu từ file

In [277]:
# df2=pd.read_csv(r'C:\Users\votua\Desktop\DATA MINING\W2\DATA\kddcup.data.corrected',header=None)
df2=pd.read_csv('kddcup.data.corrected',header=None)
df2.head(10)

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,0,tcp,http,SF,215,45076,0,0,0,0,...,0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,normal.
1,0,tcp,http,SF,162,4528,0,0,0,0,...,1,1.0,0.0,1.00,0.0,0.0,0.0,0.0,0.0,normal.
2,0,tcp,http,SF,236,1228,0,0,0,0,...,2,1.0,0.0,0.50,0.0,0.0,0.0,0.0,0.0,normal.
3,0,tcp,http,SF,233,2032,0,0,0,0,...,3,1.0,0.0,0.33,0.0,0.0,0.0,0.0,0.0,normal.
4,0,tcp,http,SF,239,486,0,0,0,0,...,4,1.0,0.0,0.25,0.0,0.0,0.0,0.0,0.0,normal.
5,0,tcp,http,SF,238,1282,0,0,0,0,...,5,1.0,0.0,0.20,0.0,0.0,0.0,0.0,0.0,normal.
6,0,tcp,http,SF,235,1337,0,0,0,0,...,6,1.0,0.0,0.17,0.0,0.0,0.0,0.0,0.0,normal.
7,0,tcp,http,SF,234,1364,0,0,0,0,...,7,1.0,0.0,0.14,0.0,0.0,0.0,0.0,0.0,normal.
8,0,tcp,http,SF,239,1295,0,0,0,0,...,8,1.0,0.0,0.12,0.0,0.0,0.0,0.0,0.0,normal.
9,0,tcp,http,SF,181,5450,0,0,0,0,...,9,1.0,0.0,0.11,0.0,0.0,0.0,0.0,0.0,normal.

Drop các cột không cần thiết

In [278]:
df2.drop(df2.columns[[1,2,3,41]],axis=1,inplace=True)
df2

,0,4,5,6,7,8,9,10,11,12,...,31,32,33,34,35,36,37,38,39,40
0,0,215,45076,0,0,0,0,0,1,0,...,0,0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.0
1,0,162,4528,0,0,0,0,0,1,0,...,1,1,1.0,0.0,1.00,0.00,0.0,0.00,0.0,0.0
2,0,236,1228,0,0,0,0,0,1,0,...,2,2,1.0,0.0,0.50,0.00,0.0,0.00,0.0,0.0
3,0,233,2032,0,0,0,0,0,1,0,...,3,3,1.0,0.0,0.33,0.00,0.0,0.00,0.0,0.0
4,0,239,486,0,0,0,0,0,1,0,...,4,4,1.0,0.0,0.25,0.00,0.0,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4898426,0,212,2288,0,0,0,0,0,1,0,...,3,255,1.0,0.0,0.33,0.05,0.0,0.01,0.0,0.0
4898427,0,219,236,0,0,0,0,0,1,0,...,4,255,1.0,0.0,0.25,0.05,0.0,0.01,0.0,0.0
4898428,0,218,3610,0,0,0,0,0,1,0,...,5,255,1.0,0.0,0.20,0.05,0.0,0.01,0.0,0.0
4898429,0,219,1234,0,0,0,0,0,1,0,...,6,255,1.0,0.0,0.17,0.05,0.0,0.01,0.0,0.0
4898430,0,219,1098,0,0,0,0,0,1,0,...,7,255,1.0,0.0,0.14,0.05,0.0,0.01,0.0,0.0

Vì để tính độ đo thích ứng (match measure) và độ đo tần suất xuất hiện ngược (inverse occurrence frequency measure) dữ liệu phải là biến category nên em sẽ rời rạc hóa các thuộc tính liên tục bằng Hàm KBinsDiscretizer

In [279]:
from sklearn.preprocessing import KBinsDiscretizer
equi_width_scaler = KBinsDiscretizer(
    n_bins=10, encode='ordinal', strategy='uniform')

df2_cp = equi_width_scaler.fit_transform(df2)

c:\Users\votua\Desktop\VE\env\lib\site-packages\sklearn\preprocessing\_discretization.py:245: UserWarning: Feature 16 is constant and will be replaced with 0.
  warnings.warn(

In [280]:
# Convert trở lại vào dataframe
# df2_cp=pd.DataFrame(df2_cp,columns=[1,2])
df2_cp=pd.DataFrame(df2_cp)
df2_cp

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,0.0,9.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,0.0,9.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,0.0,9.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4898426,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,9.0,9.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
4898427,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,9.0,9.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
4898428,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,9.0,9.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
4898429,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,9.0,9.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4898430,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,9.0,9.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [281]:
# Chuyển việc rời rạc hóa thành các bins là các số nguyên nên em sẽ convert df2_cp về sang số nguyên cho tối ưu
df2_cp=df2_cp.astype(dtype=np.int32)
# df2_cp.head()

Để tính inverse occurence frequency measure , cần phải tính tần xuất của mỗi giá trị trong 1 cột, nên em sẽ tạo một dictionary để lưu sẵn các giá trị đó, tránh phải tính đi lại nhiều lần dẫn đến hiện năng kém

In [282]:
value_counts_dict = {}

for i,column in enumerate(df2_cp.columns):
    value_counts_dict[i]=df2_cp[column].value_counts(normalize=True).to_dict()
value_counts_dict

{0: {0: 0.997679665182586,
  1: 0.001373092731121455,
  2: 0.000604683418016912,
  3: 0.00020006406132902556,
  4: 5.103675033903713e-05,
  6: 4.4912340298352675e-05,
  5: 2.8580580189860793e-05,
  7: 1.776078911798492e-05,
  9: 2.0414700135614854e-07},
 1: {0: 0.9999987751179918,
  5: 2.0414700135614854e-07,
  4: 2.0414700135614854e-07,
  9: 2.0414700135614854e-07,
  2: 2.0414700135614854e-07,
  1: 2.0414700135614854e-07,
  8: 2.0414700135614854e-07},
 2: {0: 0.999999387558996,
  3: 4.082940027122971e-07,
  9: 2.0414700135614854e-07},
 3: {0: 0.999994283883962, 9: 5.716116037972159e-06},
 4: {0: 0.9997472660123211,
  9: 0.00019802259131546408,
  3: 5.4711396363447806e-05},
 5: {0: 0.9999985709709905,
  1: 8.165880054245942e-07,
  3: 2.0414700135614854e-07,
  2: 2.0414700135614854e-07,
  9: 2.0414700135614854e-07},
 6: {0: 0.9995990552893366,
  2: 0.00017087104013509632,
  3: 0.00016556321809983645,
  1: 6.369386442311835e-05,
  5: 4.082940027122971e-07,
  9: 2.0414700135614854e-07,
  4: 2.0414700135614854e-07},
 7: {0: 0.9999744816248305,
  2: 2.1843729145107892e-05,
  4: 1.8373230122053367e-06,
  6: 1.0207350067807426e-06,
  8: 6.124410040684456e-07,
  9: 2.0414700135614854e-07},
 8: {0: 0.8564709801975368, 9: 0.14352901980246327},
 9: {0: 0.9999977543829851,
  1: 1.8373230122053367e-06,
  9: 2.0414700135614854e-07,
  2: 2.0414700135614854e-07},
 10: {0: 0.999931814901547, 9: 6.81850984529536e-05},
 11: {0: 0.9999775438298508,
  9: 1.4290290094930396e-05,
  5: 8.165880054245941e-06},
 12: {0: 0.9999969377949797,
  1: 2.653911017629931e-06,
  9: 2.0414700135614854e-07,
  2: 2.0414700135614854e-07},
 13: {0: 0.9999632535397559,
  3: 9.79905606509513e-06,
  2: 6.736851044752902e-06,
  4: 5.103675033903713e-06,
  1: 4.491234029835268e-06,
  6: 3.2663520216983766e-06,
  5: 3.2663520216983766e-06,
  7: 1.6331760108491883e-06,
  8: 1.4290290094930398e-06,
  9: 1.0207350067807426e-06},
 14: {0: 0.9999267112265131,
  5: 7.226803848007658e-05,
  9: 1.0207350067807426e-06},
 15: {0: 0.9990480625326763,
  1: 0.0009041670690063819,
  2: 4.021695926716126e-05,
  4: 1.8373230122053367e-06,
  5: 1.8373230122053367e-06,
  3: 1.8373230122053367e-06,
  6: 8.165880054245942e-07,
  8: 6.124410040684456e-07,
  7: 4.082940027122971e-07,
  9: 2.0414700135614854e-07},
 16: {0: 1.0},
 17: {0: 0.9999995917059973, 9: 4.082940027122971e-07},
 18: {0: 0.999164834617452, 9: 0.0008351653825480036},
 19: {9: 0.553725264273397,
  0: 0.20635730093983154,
  2: 0.08316050588443524,
  4: 0.06254063801245746,
  5: 0.04788206672708057,
  8: 0.021237208404078774,
  3: 0.013552094538026563,
  1: 0.011192971790354911,
  6: 0.00019577697430054643,
  7: 0.00015617245603745362},
 20: {9: 0.5511309641801629,
  0: 0.4221286367002005,
  8: 0.02119719559181297,
  1: 0.002594708387236648,
  2: 0.0013449204449343065,
  3: 0.000626731294163376,
  4: 0.00043136261386554186,
  5: 0.0002727403938118144,
  6: 0.0001582139260510151,
  7: 0.00011452646776079933},
 21: {0: 0.8202975605862367,
  9: 0.17734086690207537,
  1: 0.0013794212881634957,
  2: 0.0005648747527524629,
  5: 0.00014024898993167403,
  3: 0.000133307991885565,
  6: 3.9808665264448966e-05,
  4: 3.797134225224363e-05,
  8: 3.715475424681903e-05,
  7: 2.8784727191216942e-05},
 22: {0: 0.8213325858831124,
  9: 0.17772895035165343,
  1: 0.0004636178400798133,
  2: 0.0002014930903385186,
  5: 0.00012269234781504528,
  3: 0.00010003203066451278,
  8: 2.0618847136971003e-05,
  6: 1.4086143093574249e-05,
  4: 9.186615061026685e-06,
  7: 6.736851044752902e-06},
 23: {0: 0.9416570326294277,
  9: 0.056318441558123405,
  8: 0.0010958611032798053,
  7: 0.000369710219455985,
  1: 0.0001396365489276056,
  2: 0.00013065408086793506,
  5: 0.00012595869983674364,
  6: 8.492515256415779e-05,
  3: 7.247218548143272e-05,
  4: 5.307822035259862e-06},
 24: {0: 0.941406748405765,
  9: 0.05729508081261122,
  1: 0.0004323833488723226,
  2: 0.00029887120998540144,
  5: 0.0002594708387236648,
  3: 0.00019026500526393044,
  6: 4.2870870284791194e-05,
  8: 3.327596122105221e-05,
  4: 2.082299413832715e-05,
  7: 2.0210553134258704e-05},
 25: {9: 0.7723242401495499,
  0: 0.17456548841863853,
  1: 0.04333877521189949,
  5: 0.003214702830355271,
  2: 0.002926243117439033,
  3: 0.0017830199098446012,
  4: 0.000643267201273224,
  6: 0.0005689576927795859,
  8: 0.00038481709755634,
  7: 0.0002504883706639942},
 26: {0: 0.9871224071544541,
  9: 0.0049417864618282875,
  1: 0.002627576054454988,
  5: 0.0019075495806718519,
  6: 0.0014518934736449283,
  2: 0.0009913378385854573,
  3: 0.0004060483856973794,
  4: 0.000339496463255275,
  7: 0.00017107518713645246,
  8: 4.082940027122971e-05},
 27: {0: 0.9417507361030502,
  1: 0.01882153693703147,
  9: 0.01609127494089434,
  2: 0.010595229370384108,
  3: 0.003380878489459176,
  5: 0.003311264361996729,
  6: 0.0025663319540481433,
  4: 0.0025600033970061024,
  7: 0.0007122688877316023,
  8: 0.00021047555839818913},
 28: {9: 0.8826115954271888,
  0: 0.04233600514123808,
  1: 0.018621881169705156,
  2: 0.013751342011350165,
  3: 0.010407618276137807,
  4: 0.008737695805044514,
  5: 0.007149023840490965,
  6: 0.006375714999353875,
  7: 0.005312313269289697,
  8: 0.004696810060200909},
 29: {9: 0.7111411796961109,
  0: 0.24401262363397586,
  8: 0.006426343455690199,
  1: 0.006336110481090782,
  2: 0.006007229661906027,
  5: 0.005742246854145746,
  6: 0.005667529051649396,
  4: 0.005235962290782497,
  3: 0.005211260503618404,
  7: 0.004219514371030234},
 30: {9: 0.7267602626228684,
  0: 0.2374231667242021,
  8: 0.006608850874902596,
  1: 0.005297614685192054,
  6: 0.004984453185111723,
  5: 0.0048546156922492124,
  7: 0.00395841035629572,
  2: 0.0037583462949666944,
  4: 0.003399047572579873,
  3: 0.0029552319916316063},
 31: {0: 0.9767797076247476,
  8: 0.006114406837618005,
  9: 0.004421619902372821,
  1: 0.003968617706363527,
  6: 0.0026014452382814007,
  5: 0.0021170044040632603,
  7: 0.0013571692650156755,
  2: 0.0011895645769022774,
  4: 0.0009623489643928841,
  3: 0.00048811548024255114},
 32: {9: 0.5932779291981453,
  0: 0.37621822171221764,
  1: 0.010581551521293246,
  2: 0.006661724948253839,
  3: 0.004480822532766104,
  5: 0.004155616359605759,
  8: 0.0016978906102790873,
  4: 0.0014392363595608472,
  6: 0.000761468315058434,
  7: 0.0007255384428197519},
 33: {0: 0.9865612070477261,
  1: 0.006785642178077021,
  2: 0.0034315069457955005,
  5: 0.001810171461024969,
  9: 0.0007075735067004108,
  3: 0.00043605799489673325,
  4: 0.0001720959221432332,
  6: 8.206709454517171e-05,
  7: 1.0411497069163574e-05,
  8: 3.2663520216983766e-06},
 34: {0: 0.8204065750849608,
  9: 0.1773086116758611,
  1: 0.0013653351450699214,
  2: 0.0003684853374478481,
  3: 0.00019373550428698495,
  5: 0.00010717717571197797,
  4: 8.492515256415779e-05,
  8: 7.063486246922739e-05,
  7: 4.736210431462646e-05,
  6: 4.715795731327031e-05},
 35: {0: 0.8221161020743173,
  9: 0.17764810813911638,
  1: 6.369386442311835e-05,
  5: 3.776719525088748e-05,
  2: 2.7763992184436202e-05,
  6: 2.7559845183080052e-05,
  8: 2.1639582143751743e-05,
  3: 2.1231288141039448e-05,
  7: 2.082299413832715e-05,
  4: 1.5311025101711138e-05},
 36: {0: 0.9396090299118228,
  9: 0.05477468193386821,
  8: 0.0016560404750010768,
  1: 0.0008596630227107415,
  2: 0.0005807982188582426,
  5: 0.0005675286637700929,
  7: 0.0005228204704730964,
  6: 0.0005205748534581788,
  4: 0.00046055563505947107,
  3: 0.0004483068149781022},
 37: {0: 0.9409915134050066,
  9: 0.055152353886377084,
  8: 0.0010219598887888795,
  7: 0.0007537107290069004,
  6: 0.0006079497700386103,
  5: 0.000603254389007419,
  4: 0.00028498921389318336,
  3: 0.00025600033970061024,
  1: 0.00018230327221104063,
  2: 0.0001459651059696462}}

In [283]:
df2_cp=np.asarray(df2_cp)

Em sẽ dùng hàm NearestNeighbors trong thư viện sklearn để tính k láng giềng gần nhất cho mỗi điểm dữ liệu, dưới đây là mô tả đơn giản về  các tham số cũng như cách sử dụng hàm NearestNeighbor em tổng hợp từ documentation của thư viện sklearn

- n_neighbors: Đây là số lượng láng giềng gần nhất cần tìm kiếm. Tham số này được đặt bằng giá trị của k, là một số nguyên dương.

- algorithm: Đây là thuật toán được sử dụng để tìm kiếm láng giềng gần nhất. Có thể lựa chọn giữa các giá trị "auto", "ball_tree", "kd_tree", hoặc "brute". Thông thường, giá trị "auto" sẽ tự động chọn thuật toán phù hợp dựa trên dữ liệu đầu vào.

- metric: Đây là hàm khoảng cách được sử dụng để tính khoảng cách giữa các điểm dữ liệu. Có thể lựa chọn giữa các hàm khoảng cách có sẵn trong sklearn hoặc tự định nghĩa hàm khoảng cách riêng. Ví dụ: 'euclidean', 'manhattan', 'minkowski', vv.

- metric_params: Đây là tham số tùy chọn được truyền vào hàm khoảng cách nếu cần thiết. Thường thì không cần thiết phải sử dụng tham số này, và để mặc định là None.

- Sau khi khởi tạo đối tượng NearestNeighbors và fit dữ liệu vào model bằng phương thức fit(), chúng ta có thể sử dụng phương thức kneighbors() để tìm kiếm láng giềng gần nhất cho một điểm dữ liệu mới (hoặc một tập điểm dữ liệu mới). Kết quả trả về gồm hai mảng: distances là khoảng cách từ điểm dữ liệu mới đến k láng giềng gần nhất, và indices là chỉ số của các láng giềng gần nhất trong tập dữ liệu huấn luyện ban đầu.

Vì độ đo match measure và inverse occurrence frequency measure là 1 simility function, tức là sẽ cho ``giá trị càng lớn nếu 2 điểm càng gần nhau``, trong khi hàm NearestNeighbors nhận vào hàm tính khoảng cách distance function (``2 điểm càng gần nhau thì khoảng cách càng thấp``), nên lúc code hàm match_measure và inverse_occurrence_frequency_measure, em sẽ lấy giá trị âm để đúng với yêu cầu của hàm NearestNeighbors.

In [284]:
# Hàm tính match measure giữa 2 vectors
def match_measure(X,Y):
    return -np.count_nonzero(X==Y)

def inverse_occurrence_frequency_measure(X, Y, value_counts_dict):
    # Tạo một mảng 1D chứa các giá trị frequency tương ứng với các phần tử trong X
    frequencies = np.array([value_counts_dict[i][x] for i, x in enumerate(X)])
    
    # Tìm các vị trí trong X và Y mà giá trị tại đó bằng nhau
    equal_indices = np.where(X == Y)
    
    # Tính tổng của nghịch đảo bình phương của các frequency tại các vị trí trên
    S = np.sum(1 / (frequencies[equal_indices] ** 2))
    
    return -S

Sử dụng hàm NearestNeighbors để tính k láng giềng gần nhất của mỗi điểm dữ liệu

Vì dữ liệu khá lớn (~5 triệu dòng), nếu muốn tìm k láng giềng gần nhất cho mỗi điểm dữ liệu thì tương đương với việc tính 5.000.000*4.999.999/2 khoảng cách, và muốn tính mỗi khoảng cách phải loop qua tất cả các cột, tức độ phức tạp thuật toán nếu dùng cách vét cạn (brute) là O(n x n x p) hoặc O(n x log(n) x p) nếu dùng ball_tree ( với n là số dòng và p là số cột)

Với độ phức tạp thuật toán là O(n x n x p) hay O(n x log(n) x p) thì việc tính toán trên dữ liệu gần 5 triệu dòng sẽ tốn rất nhiều thời gian, nên em chỉ sẽ tính cho 1000 điểm dữ liệu đầu tiên

## Tính k láng giềng gần nhất bằng độ đo match measure

Thuật toán em dùng để tính là ball_tree, bằng cách sử dụng ball_tree thay vì brute, việc này giảm độ phức tạp thuật toán từ O(n x n x p) xuống còn O (n x log(n) x p)

In [285]:
from sklearn.neighbors import NearestNeighbors

neighbor_match=NearestNeighbors(n_neighbors= 20,metric=match_measure,algorithm='ball_tree').fit(df2_cp[:1000,:])
# result1_arr=neighbor_match.kneighbors(df2_cp[:1000,:])
result1_arr=neighbor_match.kneighbors()

Ta có result1_arr là 1 tuple gồm 2 ma trận, với ma trận đầu tiên là khoảng cách từ mỗi điểm đến k điểm gần nhất , ma trận thứ hai tương ứng là index của các điểm gần nhất đó

In [286]:
print(result1_arr[1])
print(result1_arr[0])

[[11 19 24 ... 10  9  8]
 [ 8 20 19 ...  4  7  3]
 [ 8 20 19 ...  4  7  3]
 ...
 [19 25 15 ...  3  7  9]
 [19 25 15 ...  3  7  9]
 [27 29 32 ... 11 22 10]]
[[-37. -37. -37. ... -36. -36. -36.]
 [-37. -37. -37. ... -37. -37. -37.]
 [-37. -37. -37. ... -37. -37. -37.]
 ...
 [-37. -37. -37. ... -36. -36. -36.]
 [-37. -37. -37. ... -36. -36. -36.]
 [-37. -37. -37. ... -36. -36. -35.]]

In [287]:
print('k lang gieng gan nhat voi diem 0 : ')
print(result1_arr[1][0,:]) # In ra k láng giềng gần nhất của điểm dữ liệu 0 (dòng 0)
print('khoang cach tuong ung')
print(-result1_arr[0][0,:]) # In ra độ đo match measure tương ứng (không lấy dấu âm)

k lang gieng gan nhat voi diem 0 :
[11 19 24 15 18 20 23 13 14 16 17 25 21 22 12  4  7 10  9  8]
khoang cach tuong ung
[37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 37. 36. 36. 36.
 36. 36.]

Em sẽ kiểm tra lại bằng cách tính trực tiếp

Ở đây em chỉ kiểm tra với khoảng cách lớn nhất (37), vì ví dụ như có nhiều hơn k điểm với khoảng cách bằng nhau, thì khi lấy k điểm láng giềng có thể sẽ khác nhau

Ví dụ như có 3 điểm (1, 2, 3 ) có khoảng cách bằng nhau tới điểm 0 , thì khi lấy 2 láng giềng của điểm 0 thì có thể là (1, 2) ,(2, 3) hay (1, 3)

In [288]:
print('k lang gieng gan nhat voi diem 0 : ')
print(np.argsort(np.array([match_measure(df2_cp[0,:],df2_cp[i]) for i in range(0,1000)]))[1:21]) # In ra k láng giềng gần nhất của điểm dữ liệu 0 (dòng 0)
print('khoang cach tuong ung')
print(-np.sort(np.array([match_measure(df2_cp[0,:],df2_cp[i,:]) for i in range(0,1000)]))[1:21]) # In ra độ đo match measure tương ứng (không lấy dấu âm)

k lang gieng gan nhat voi diem 0 :
[ 25  24  23  22  21  20  19  17  16  15  14  13  18  11  12 531 532 533
 534 535]
khoang cach tuong ung
[37 37 37 37 37 37 37 37 37 37 37 37 37 37 37 36 36 36 36 36]

Kết quả kiểm tra 15 điểm gần với 0 nhất với khoảng cách là 37 là : 11 19 24 15 18 20 23 13 14 16 17 25 21 22 12

## Tính k láng giềng gần nhất bằng độ đo inverse occurence frequency measure

Vì inverse_occurrence_frequency_measure không dùng thuật toán ball_tree được nên em chỉ sử dụng thuật toán brute thông thường với độ phức tạp O(n x n x p), nên e chỉ tính cho 1000 điểm dữ liệu đầu tiền

In [289]:
from sklearn.neighbors import NearestNeighbors

neighbor_iofm=NearestNeighbors(n_neighbors=20 ,metric=inverse_occurrence_frequency_measure,metric_params={'value_counts_dict':value_counts_dict}).fit(df2_cp[:1000,])
result2_arr=neighbor_iofm.kneighbors()

Ta có result1_arr là 1 tuple gồm 2 ma trận, với ma trận đầu tiên là khoảng cách từ mỗi điểm đến k điểm gần nhất , ma trận thứ hai tương ứng là index của các điểm gần nhất đó

In [290]:
print(result2_arr[1])
print(result2_arr[0])

[[ 14  12  11 ...   3   4   1]
 [ 13  15   4 ...  12   6  10]
 [580 453 458 ...  93 541 266]
 ...
 [529 528 527 ... 532 504 531]
 [529 528 527 ... 532 504 531]
 [321 365 323 ... 313 539 319]]
[[  -693.79603563   -693.79603563   -693.79603563 ...   -686.73090254
    -686.73090254   -686.73090254]
 [  -688.62419477   -688.62419477   -688.62419477 ...   -688.62419477
    -688.62419477   -688.62419477]
 [-58578.56796211 -58578.56796211 -58578.56796211 ... -58578.56796211
  -58578.56796211 -58578.56796211]
 ...
 [  -680.87187748   -680.87187748   -680.87187748 ...   -680.87187748
    -680.87187748   -680.87187748]
 [  -680.87187748   -680.87187748   -680.87187748 ...   -680.87187748
    -680.87187748   -680.87187748]
 [ -3006.65991831  -3006.65991831  -3006.65991831 ...  -3006.65991831
   -3006.65991831  -3006.65991831]]

In [291]:
print('k lang gieng gan nhat voi diem 0 : ')
print(result2_arr[1][0,:]) # In ra k láng giềng gần nhất của điểm dữ liệu 0 (dòng 0)
print('khoang cach tuong ung')
print(-result2_arr[0][0,:]) # In ra độ đo inverse occurence frequency measure tương ứng (không lấy dấu âm)

k lang gieng gan nhat voi diem 0 :
[14 12 11 16 13 15 17 20 19 21 22 23 24 25 18  5  2  3  4  1]
khoang cach tuong ung
[693.79603563 693.79603563 693.79603563 693.79603563 693.79603563
 693.79603563 693.79603563 693.79603563 693.79603563 693.79603563
 693.79603563 693.79603563 693.79603563 693.79603563 693.79603563
 686.73090254 686.73090254 686.73090254 686.73090254 686.73090254]

Em sẽ kiểm tra lại bằng cách tính trực tiếp

Ở đây em chỉ kiểm tra với khoảng cách lớn nhất (693.79), vì ví dụ như có nhiều hơn k điểm với khoảng cách là như nhau, thì khi lấy k điểm láng giềng có thể sẽ khác nhau

Ví dụ như có 3 điểm (1, 2, 3 ) có khoảng cách bằng nhau tới điểm 0 , thì khi lấy 2 láng giềng của điểm 0 thì có thể là (1, 2) ,(2, 3) hay (1, 3)

In [292]:
print('k lang gieng gan nhat voi diem 0 : ')
print(np.argsort(np.array([inverse_occurrence_frequency_measure(df2_cp[0,:],df2_cp[i],value_counts_dict) for i in range(0,1000)]))[1:21]) # In ra k láng giềng gần nhất của điểm dữ liệu 0 (dòng 0)
print('khoang cach tuong ung')
print(-np.sort(np.array([inverse_occurrence_frequency_measure(df2_cp[0,:],df2_cp[i,:],value_counts_dict) for i in range(0,1000)]))[1:21]) # In ra độ đo inverse occurence frequency measure tương ứng (không lấy dấu âm)

k lang gieng gan nhat voi diem 0 :
[25 24 23 21 20 19 18 17 16 15 14 13 22 11 12  1  3  4  5  2]
khoang cach tuong ung
[693.79603563 693.79603563 693.79603563 693.79603563 693.79603563
 693.79603563 693.79603563 693.79603563 693.79603563 693.79603563
 693.79603563 693.79603563 693.79603563 693.79603563 693.79603563
 686.73090254 686.73090254 686.73090254 686.73090254 686.73090254]

Kết quả kiểm tra 15 điểm gần với 0 nhất với khoảng cách là 37 là : 25 24 23 21 20 19 18 17 16 15 14 13 22 11 12

## Bonus

Có thể dùng PCA để giảm chiều dữ liệu xuống , khi đó tính khoảng cách sẽ nhanh hơn ạ